// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: isochrones.proto

package protos_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User's request for isochrones
type IsochronesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max cost restrictions for single isochrone. Should be in range [0,+Inf]. Minumim is 0.
	// Example: 2100.0
	MaxCost *float64 `protobuf:"fixed64,1,opt,name=max_cost,json=maxCost,proto3,oneof" json:"max_cost,omitempty"`
	// Max radius of search for nearest vertex (Optional, default is 25.0, should be in range [0,+Inf])
	// Example: 25.0
	MaxNearestRadius *float64 `protobuf:"fixed64,2,opt,name=max_nearest_radius,json=maxNearestRadius,proto3,oneof" json:"max_nearest_radius,omitempty"`
	// Longitude
	// Example: 37.601249363208915
	Lon float64 `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	// Latitude
	// Example: 55.745374309126895
	Lat           float64 `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsochronesRequest) Reset() {
	*x = IsochronesRequest{}
	mi := &file_isochrones_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsochronesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsochronesRequest) ProtoMessage() {}

func (x *IsochronesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isochrones_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsochronesRequest.ProtoReflect.Descriptor instead.
func (*IsochronesRequest) Descriptor() ([]byte, []int) {
	return file_isochrones_proto_rawDescGZIP(), []int{0}
}

func (x *IsochronesRequest) GetMaxCost() float64 {
	if x != nil && x.MaxCost != nil {
		return *x.MaxCost
	}
	return 0
}

func (x *IsochronesRequest) GetMaxNearestRadius() float64 {
	if x != nil && x.MaxNearestRadius != nil {
		return *x.MaxNearestRadius
	}
	return 0
}

func (x *IsochronesRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *IsochronesRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

// Server's response for isochrones request
type IsochronesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of isochrones
	Isochrones []*Isochrone `protobuf:"bytes,1,rep,name=isochrones,proto3" json:"isochrones,omitempty"`
	// List of warnings
	Warnings      []string `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsochronesResponse) Reset() {
	*x = IsochronesResponse{}
	mi := &file_isochrones_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsochronesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsochronesResponse) ProtoMessage() {}

func (x *IsochronesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isochrones_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsochronesResponse.ProtoReflect.Descriptor instead.
func (*IsochronesResponse) Descriptor() ([]byte, []int) {
	return file_isochrones_proto_rawDescGZIP(), []int{1}
}

func (x *IsochronesResponse) GetIsochrones() []*Isochrone {
	if x != nil {
		return x.Isochrones
	}
	return nil
}

func (x *IsochronesResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Single isochrone information
type Isochrone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Isochrone ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Travel cost to the target vertex
	Cost float64 `protobuf:"fixed64,2,opt,name=cost,proto3" json:"cost,omitempty"`
	// Vertex ID in the graph
	VertexId int64 `protobuf:"varint,3,opt,name=vertex_id,json=vertexId,proto3" json:"vertex_id,omitempty"`
	// Longitude, Latitude
	Point         *GeoPoint `protobuf:"bytes,4,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Isochrone) Reset() {
	*x = Isochrone{}
	mi := &file_isochrones_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Isochrone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Isochrone) ProtoMessage() {}

func (x *Isochrone) ProtoReflect() protoreflect.Message {
	mi := &file_isochrones_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Isochrone.ProtoReflect.Descriptor instead.
func (*Isochrone) Descriptor() ([]byte, []int) {
	return file_isochrones_proto_rawDescGZIP(), []int{2}
}

func (x *Isochrone) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Isochrone) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Isochrone) GetVertexId() int64 {
	if x != nil {
		return x.VertexId
	}
	return 0
}

func (x *Isochrone) GetPoint() *GeoPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

var File_isochrones_proto protoreflect.FileDescriptor

const file_isochrones_proto_rawDesc = "" +
	"\n" +
	"\x10isochrones.proto\x12\ahorizon\x1a\vpoint.proto\"\xae\x01\n" +
	"\x11IsochronesRequest\x12\x1e\n" +
	"\bmax_cost\x18\x01 \x01(\x01H\x00R\amaxCost\x88\x01\x01\x121\n" +
	"\x12max_nearest_radius\x18\x02 \x01(\x01H\x01R\x10maxNearestRadius\x88\x01\x01\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03latB\v\n" +
	"\t_max_costB\x15\n" +
	"\x13_max_nearest_radius\"d\n" +
	"\x12IsochronesResponse\x122\n" +
	"\n" +
	"isochrones\x18\x01 \x03(\v2\x12.horizon.IsochroneR\n" +
	"isochrones\x12\x1a\n" +
	"\bwarnings\x18\x02 \x03(\tR\bwarnings\"u\n" +
	"\tIsochrone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\x01R\x04cost\x12\x1b\n" +
	"\tvertex_id\x18\x03 \x01(\x03R\bvertexId\x12'\n" +
	"\x05point\x18\x04 \x01(\v2\x11.horizon.GeoPointR\x05pointB\x0eZ\f./;protos_pbb\x06proto3"

var (
	file_isochrones_proto_rawDescOnce sync.Once
	file_isochrones_proto_rawDescData []byte
)

func file_isochrones_proto_rawDescGZIP() []byte {
	file_isochrones_proto_rawDescOnce.Do(func() {
		file_isochrones_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_isochrones_proto_rawDesc), len(file_isochrones_proto_rawDesc)))
	})
	return file_isochrones_proto_rawDescData
}

var file_isochrones_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_isochrones_proto_goTypes = []any{
	(*IsochronesRequest)(nil),  // 0: horizon.IsochronesRequest
	(*IsochronesResponse)(nil), // 1: horizon.IsochronesResponse
	(*Isochrone)(nil),          // 2: horizon.Isochrone
	(*GeoPoint)(nil),           // 3: horizon.GeoPoint
}
var file_isochrones_proto_depIdxs = []int32{
	2, // 0: horizon.IsochronesResponse.isochrones:type_name -> horizon.Isochrone
	3, // 1: horizon.Isochrone.point:type_name -> horizon.GeoPoint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_isochrones_proto_init() }
func file_isochrones_proto_init() {
	if File_isochrones_proto != nil {
		return
	}
	file_point_proto_init()
	file_isochrones_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_isochrones_proto_rawDesc), len(file_isochrones_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_isochrones_proto_goTypes,
		DependencyIndexes: file_isochrones_proto_depIdxs,
		MessageInfos:      file_isochrones_proto_msgTypes,
	}.Build()
	File_isochrones_proto = out.File
	file_isochrones_proto_goTypes = nil
	file_isochrones_proto_depIdxs = nil
}
