// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.2
// source: isochrones.proto

package protos_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User's request for isochrones
type IsochronesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Max cost restrictions for single isochrone. Should be in range [0,+Inf]. Minumim is 0.
	// Example: 2100.0
	MaxCost *float64 `protobuf:"fixed64,1,opt,name=max_cost,json=maxCost,proto3,oneof" json:"max_cost,omitempty"`
	// Max radius of search for nearest vertex (Optional, default is 25.0, should be in range [0,+Inf])
	// Example: 25.0
	MaxNearestRadius *float64 `protobuf:"fixed64,2,opt,name=max_nearest_radius,json=maxNearestRadius,proto3,oneof" json:"max_nearest_radius,omitempty"`
	// Longitude
	// Example: 37.601249363208915
	Lon float64 `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	// Latitude
	// Example: 55.745374309126895
	Lat float64 `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
}

func (x *IsochronesRequest) Reset() {
	*x = IsochronesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isochrones_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsochronesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsochronesRequest) ProtoMessage() {}

func (x *IsochronesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isochrones_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsochronesRequest.ProtoReflect.Descriptor instead.
func (*IsochronesRequest) Descriptor() ([]byte, []int) {
	return file_isochrones_proto_rawDescGZIP(), []int{0}
}

func (x *IsochronesRequest) GetMaxCost() float64 {
	if x != nil && x.MaxCost != nil {
		return *x.MaxCost
	}
	return 0
}

func (x *IsochronesRequest) GetMaxNearestRadius() float64 {
	if x != nil && x.MaxNearestRadius != nil {
		return *x.MaxNearestRadius
	}
	return 0
}

func (x *IsochronesRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *IsochronesRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

// Server's response for isochrones request
type IsochronesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of isochrones
	Isochrones []*Isochrone `protobuf:"bytes,1,rep,name=isochrones,proto3" json:"isochrones,omitempty"`
	// List of warnings
	Warnings []string `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
}

func (x *IsochronesResponse) Reset() {
	*x = IsochronesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isochrones_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsochronesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsochronesResponse) ProtoMessage() {}

func (x *IsochronesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isochrones_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsochronesResponse.ProtoReflect.Descriptor instead.
func (*IsochronesResponse) Descriptor() ([]byte, []int) {
	return file_isochrones_proto_rawDescGZIP(), []int{1}
}

func (x *IsochronesResponse) GetIsochrones() []*Isochrone {
	if x != nil {
		return x.Isochrones
	}
	return nil
}

func (x *IsochronesResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Single isochrone information
type Isochrone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Isochrone ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Travel cost to the target vertex
	Cost float64 `protobuf:"fixed64,2,opt,name=cost,proto3" json:"cost,omitempty"`
	// Vertex ID in the graph
	VertexId int64 `protobuf:"varint,3,opt,name=vertex_id,json=vertexId,proto3" json:"vertex_id,omitempty"`
	// Longitude, Latitude
	Point *GeoPoint `protobuf:"bytes,4,opt,name=point,proto3" json:"point,omitempty"`
}

func (x *Isochrone) Reset() {
	*x = Isochrone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isochrones_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Isochrone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Isochrone) ProtoMessage() {}

func (x *Isochrone) ProtoReflect() protoreflect.Message {
	mi := &file_isochrones_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Isochrone.ProtoReflect.Descriptor instead.
func (*Isochrone) Descriptor() ([]byte, []int) {
	return file_isochrones_proto_rawDescGZIP(), []int{2}
}

func (x *Isochrone) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Isochrone) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Isochrone) GetVertexId() int64 {
	if x != nil {
		return x.VertexId
	}
	return 0
}

func (x *Isochrone) GetPoint() *GeoPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

var File_isochrones_proto protoreflect.FileDescriptor

var file_isochrones_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x73, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x1a, 0x0b, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x01, 0x0a, 0x11, 0x49, 0x73, 0x6f,
	0x63, 0x68, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x48, 0x00, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x73, 0x74, 0x88, 0x01, 0x01, 0x12, 0x31,
	0x0a, 0x12, 0x6d, 0x61, 0x78, 0x5f, 0x6e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x61,
	0x64, 0x69, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x10, 0x6d, 0x61,
	0x78, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x88, 0x01,
	0x01, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x6c, 0x61, 0x74, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f,
	0x73, 0x74, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x6e, 0x65, 0x61, 0x72, 0x65,
	0x73, 0x74, 0x5f, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x22, 0x64, 0x0a, 0x12, 0x49, 0x73, 0x6f,
	0x63, 0x68, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x32, 0x0a, 0x0a, 0x69, 0x73, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x2e, 0x49, 0x73,
	0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x65, 0x52, 0x0a, 0x69, 0x73, 0x6f, 0x63, 0x68, 0x72, 0x6f,
	0x6e, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x22,
	0x75, 0x0a, 0x09, 0x49, 0x73, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x49, 0x64, 0x12, 0x27, 0x0a,
	0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_isochrones_proto_rawDescOnce sync.Once
	file_isochrones_proto_rawDescData = file_isochrones_proto_rawDesc
)

func file_isochrones_proto_rawDescGZIP() []byte {
	file_isochrones_proto_rawDescOnce.Do(func() {
		file_isochrones_proto_rawDescData = protoimpl.X.CompressGZIP(file_isochrones_proto_rawDescData)
	})
	return file_isochrones_proto_rawDescData
}

var file_isochrones_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_isochrones_proto_goTypes = []interface{}{
	(*IsochronesRequest)(nil),  // 0: horizon.IsochronesRequest
	(*IsochronesResponse)(nil), // 1: horizon.IsochronesResponse
	(*Isochrone)(nil),          // 2: horizon.Isochrone
	(*GeoPoint)(nil),           // 3: horizon.GeoPoint
}
var file_isochrones_proto_depIdxs = []int32{
	2, // 0: horizon.IsochronesResponse.isochrones:type_name -> horizon.Isochrone
	3, // 1: horizon.Isochrone.point:type_name -> horizon.GeoPoint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_isochrones_proto_init() }
func file_isochrones_proto_init() {
	if File_isochrones_proto != nil {
		return
	}
	file_point_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_isochrones_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsochronesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isochrones_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsochronesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isochrones_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Isochrone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_isochrones_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_isochrones_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_isochrones_proto_goTypes,
		DependencyIndexes: file_isochrones_proto_depIdxs,
		MessageInfos:      file_isochrones_proto_msgTypes,
	}.Build()
	File_isochrones_proto = out.File
	file_isochrones_proto_rawDesc = nil
	file_isochrones_proto_goTypes = nil
	file_isochrones_proto_depIdxs = nil
}
