// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.2
// source: map_match.proto

package protos_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @todo
	Req int64 `protobuf:"varint,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *MapMatchRequest) Reset() {
	*x = MapMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_match_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMatchRequest) ProtoMessage() {}

func (x *MapMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_match_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMatchRequest.ProtoReflect.Descriptor instead.
func (*MapMatchRequest) Descriptor() ([]byte, []int) {
	return file_map_match_proto_rawDescGZIP(), []int{0}
}

func (x *MapMatchRequest) GetReq() int64 {
	if x != nil {
		return x.Req
	}
	return 0
}

type MapMatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @todo
	Res int64 `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *MapMatchResponse) Reset() {
	*x = MapMatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_match_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMatchResponse) ProtoMessage() {}

func (x *MapMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_match_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMatchResponse.ProtoReflect.Descriptor instead.
func (*MapMatchResponse) Descriptor() ([]byte, []int) {
	return file_map_match_proto_rawDescGZIP(), []int{1}
}

func (x *MapMatchResponse) GetRes() int64 {
	if x != nil {
		return x.Res
	}
	return 0
}

var File_map_match_proto protoreflect.FileDescriptor

var file_map_match_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x61, 0x70, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x22, 0x23, 0x0a, 0x0f, 0x4d, 0x61,
	0x70, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22,
	0x24, 0x0a, 0x10, 0x4d, 0x61, 0x70, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x72, 0x65, 0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_map_match_proto_rawDescOnce sync.Once
	file_map_match_proto_rawDescData = file_map_match_proto_rawDesc
)

func file_map_match_proto_rawDescGZIP() []byte {
	file_map_match_proto_rawDescOnce.Do(func() {
		file_map_match_proto_rawDescData = protoimpl.X.CompressGZIP(file_map_match_proto_rawDescData)
	})
	return file_map_match_proto_rawDescData
}

var file_map_match_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_map_match_proto_goTypes = []interface{}{
	(*MapMatchRequest)(nil),  // 0: horizon.MapMatchRequest
	(*MapMatchResponse)(nil), // 1: horizon.MapMatchResponse
}
var file_map_match_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_map_match_proto_init() }
func file_map_match_proto_init() {
	if File_map_match_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_map_match_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_match_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapMatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_map_match_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_map_match_proto_goTypes,
		DependencyIndexes: file_map_match_proto_depIdxs,
		MessageInfos:      file_map_match_proto_msgTypes,
	}.Build()
	File_map_match_proto = out.File
	file_map_match_proto_rawDesc = nil
	file_map_match_proto_goTypes = nil
	file_map_match_proto_depIdxs = nil
}
