// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: service.proto

package protos_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_RunMapMatch_FullMethodName   = "/horizon.Service/RunMapMatch"
	Service_GetSP_FullMethodName         = "/horizon.Service/GetSP"
	Service_GetIsochrones_FullMethodName = "/horizon.Service/GetIsochrones"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	RunMapMatch(ctx context.Context, in *MapMatchRequest, opts ...grpc.CallOption) (*MapMatchResponse, error)
	GetSP(ctx context.Context, in *SPRequest, opts ...grpc.CallOption) (*SPResponse, error)
	GetIsochrones(ctx context.Context, in *IsochronesRequest, opts ...grpc.CallOption) (*IsochronesResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) RunMapMatch(ctx context.Context, in *MapMatchRequest, opts ...grpc.CallOption) (*MapMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapMatchResponse)
	err := c.cc.Invoke(ctx, Service_RunMapMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetSP(ctx context.Context, in *SPRequest, opts ...grpc.CallOption) (*SPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SPResponse)
	err := c.cc.Invoke(ctx, Service_GetSP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetIsochrones(ctx context.Context, in *IsochronesRequest, opts ...grpc.CallOption) (*IsochronesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsochronesResponse)
	err := c.cc.Invoke(ctx, Service_GetIsochrones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	RunMapMatch(context.Context, *MapMatchRequest) (*MapMatchResponse, error)
	GetSP(context.Context, *SPRequest) (*SPResponse, error)
	GetIsochrones(context.Context, *IsochronesRequest) (*IsochronesResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) RunMapMatch(context.Context, *MapMatchRequest) (*MapMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunMapMatch not implemented")
}
func (UnimplementedServiceServer) GetSP(context.Context, *SPRequest) (*SPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSP not implemented")
}
func (UnimplementedServiceServer) GetIsochrones(context.Context, *IsochronesRequest) (*IsochronesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIsochrones not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call pancis, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_RunMapMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).RunMapMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_RunMapMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).RunMapMatch(ctx, req.(*MapMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetSP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetSP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetSP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetSP(ctx, req.(*SPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetIsochrones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsochronesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetIsochrones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetIsochrones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetIsochrones(ctx, req.(*IsochronesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "horizon.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunMapMatch",
			Handler:    _Service_RunMapMatch_Handler,
		},
		{
			MethodName: "GetSP",
			Handler:    _Service_GetSP_Handler,
		},
		{
			MethodName: "GetIsochrones",
			Handler:    _Service_GetIsochrones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
