// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: service.proto

package protos_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\ahorizon\x1a\x0fmap_match.proto\x1a\x13shortest_path.proto\x1a\x10isochrones.proto2\xcf\x01\n" +
	"\aService\x12D\n" +
	"\vRunMapMatch\x12\x18.horizon.MapMatchRequest\x1a\x19.horizon.MapMatchResponse\"\x00\x122\n" +
	"\x05GetSP\x12\x12.horizon.SPRequest\x1a\x13.horizon.SPResponse\"\x00\x12J\n" +
	"\rGetIsochrones\x12\x1a.horizon.IsochronesRequest\x1a\x1b.horizon.IsochronesResponse\"\x00B\x0eZ\f./;protos_pbb\x06proto3"

var file_service_proto_goTypes = []any{
	(*MapMatchRequest)(nil),    // 0: horizon.MapMatchRequest
	(*SPRequest)(nil),          // 1: horizon.SPRequest
	(*IsochronesRequest)(nil),  // 2: horizon.IsochronesRequest
	(*MapMatchResponse)(nil),   // 3: horizon.MapMatchResponse
	(*SPResponse)(nil),         // 4: horizon.SPResponse
	(*IsochronesResponse)(nil), // 5: horizon.IsochronesResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: horizon.Service.RunMapMatch:input_type -> horizon.MapMatchRequest
	1, // 1: horizon.Service.GetSP:input_type -> horizon.SPRequest
	2, // 2: horizon.Service.GetIsochrones:input_type -> horizon.IsochronesRequest
	3, // 3: horizon.Service.RunMapMatch:output_type -> horizon.MapMatchResponse
	4, // 4: horizon.Service.GetSP:output_type -> horizon.SPResponse
	5, // 5: horizon.Service.GetIsochrones:output_type -> horizon.IsochronesResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_map_match_proto_init()
	file_shortest_path_proto_init()
	file_isochrones_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
