// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.2
// source: shortest_path.proto

package protos_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User's request for finding shortest path
type SPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Max radius of search for potential candidates (in range [7, 50], default is 25.0)
	// Example: 10.0
	StateRadius *float64 `protobuf:"fixed64,1,opt,name=state_radius,json=stateRadius,proto3,oneof" json:"state_radius,omitempty"`
	// Set of GPS data
	Gps []*GeoPoint `protobuf:"bytes,2,rep,name=gps,proto3" json:"gps,omitempty"`
}

func (x *SPRequest) Reset() {
	*x = SPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortest_path_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPRequest) ProtoMessage() {}

func (x *SPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortest_path_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPRequest.ProtoReflect.Descriptor instead.
func (*SPRequest) Descriptor() ([]byte, []int) {
	return file_shortest_path_proto_rawDescGZIP(), []int{0}
}

func (x *SPRequest) GetStateRadius() float64 {
	if x != nil && x.StateRadius != nil {
		return *x.StateRadius
	}
	return 0
}

func (x *SPRequest) GetGps() []*GeoPoint {
	if x != nil {
		return x.Gps
	}
	return nil
}

// Server's response for shortest path request
type SPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of edges in a path
	Data []*EdgeInfo `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// List of warnings
	Warnings []string `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
}

func (x *SPResponse) Reset() {
	*x = SPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortest_path_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPResponse) ProtoMessage() {}

func (x *SPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortest_path_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPResponse.ProtoReflect.Descriptor instead.
func (*SPResponse) Descriptor() ([]byte, []int) {
	return file_shortest_path_proto_rawDescGZIP(), []int{1}
}

func (x *SPResponse) GetData() []*EdgeInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SPResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Edge information
type EdgeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EdgeId int64 `protobuf:"varint,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	// Travel cost to the target vertex
	Weight float64 `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// Line
	Geom []*GeoPoint `protobuf:"bytes,3,rep,name=geom,proto3" json:"geom,omitempty"`
}

func (x *EdgeInfo) Reset() {
	*x = EdgeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortest_path_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EdgeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeInfo) ProtoMessage() {}

func (x *EdgeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shortest_path_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeInfo.ProtoReflect.Descriptor instead.
func (*EdgeInfo) Descriptor() ([]byte, []int) {
	return file_shortest_path_proto_rawDescGZIP(), []int{2}
}

func (x *EdgeInfo) GetEdgeId() int64 {
	if x != nil {
		return x.EdgeId
	}
	return 0
}

func (x *EdgeInfo) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *EdgeInfo) GetGeom() []*GeoPoint {
	if x != nil {
		return x.Geom
	}
	return nil
}

var File_shortest_path_proto protoreflect.FileDescriptor

var file_shortest_path_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x1a, 0x0b,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x09, 0x53,
	0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x5f, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00,
	0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x88, 0x01, 0x01,
	0x12, 0x23, 0x0a, 0x03, 0x67, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x03, 0x67, 0x70, 0x73, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x22, 0x4f, 0x0a, 0x0a, 0x53, 0x50, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x2e, 0x45, 0x64, 0x67,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x77,
	0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x77,
	0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x62, 0x0a, 0x08, 0x45, 0x64, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x65, 0x64, 0x67, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x67, 0x65, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x6f,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x04, 0x67, 0x65, 0x6f, 0x6d, 0x42, 0x0e, 0x5a, 0x0c, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_shortest_path_proto_rawDescOnce sync.Once
	file_shortest_path_proto_rawDescData = file_shortest_path_proto_rawDesc
)

func file_shortest_path_proto_rawDescGZIP() []byte {
	file_shortest_path_proto_rawDescOnce.Do(func() {
		file_shortest_path_proto_rawDescData = protoimpl.X.CompressGZIP(file_shortest_path_proto_rawDescData)
	})
	return file_shortest_path_proto_rawDescData
}

var file_shortest_path_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shortest_path_proto_goTypes = []interface{}{
	(*SPRequest)(nil),  // 0: horizon.SPRequest
	(*SPResponse)(nil), // 1: horizon.SPResponse
	(*EdgeInfo)(nil),   // 2: horizon.EdgeInfo
	(*GeoPoint)(nil),   // 3: horizon.GeoPoint
}
var file_shortest_path_proto_depIdxs = []int32{
	3, // 0: horizon.SPRequest.gps:type_name -> horizon.GeoPoint
	2, // 1: horizon.SPResponse.data:type_name -> horizon.EdgeInfo
	3, // 2: horizon.EdgeInfo.geom:type_name -> horizon.GeoPoint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shortest_path_proto_init() }
func file_shortest_path_proto_init() {
	if File_shortest_path_proto != nil {
		return
	}
	file_point_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_shortest_path_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shortest_path_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shortest_path_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EdgeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_shortest_path_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shortest_path_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shortest_path_proto_goTypes,
		DependencyIndexes: file_shortest_path_proto_depIdxs,
		MessageInfos:      file_shortest_path_proto_msgTypes,
	}.Build()
	File_shortest_path_proto = out.File
	file_shortest_path_proto_rawDesc = nil
	file_shortest_path_proto_goTypes = nil
	file_shortest_path_proto_depIdxs = nil
}
