// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.2
// source: shortest_path.proto

package protos_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @todo
	Req int64 `protobuf:"varint,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *SPRequest) Reset() {
	*x = SPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortest_path_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPRequest) ProtoMessage() {}

func (x *SPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortest_path_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPRequest.ProtoReflect.Descriptor instead.
func (*SPRequest) Descriptor() ([]byte, []int) {
	return file_shortest_path_proto_rawDescGZIP(), []int{0}
}

func (x *SPRequest) GetReq() int64 {
	if x != nil {
		return x.Req
	}
	return 0
}

type SPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @todo
	Res int64 `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *SPResponse) Reset() {
	*x = SPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortest_path_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPResponse) ProtoMessage() {}

func (x *SPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortest_path_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPResponse.ProtoReflect.Descriptor instead.
func (*SPResponse) Descriptor() ([]byte, []int) {
	return file_shortest_path_proto_rawDescGZIP(), []int{1}
}

func (x *SPResponse) GetRes() int64 {
	if x != nil {
		return x.Res
	}
	return 0
}

var File_shortest_path_proto protoreflect.FileDescriptor

var file_shortest_path_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x6f, 0x6e, 0x22, 0x1d,
	0x0a, 0x09, 0x53, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x1e, 0x0a,
	0x0a, 0x53, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x65, 0x73, 0x42, 0x0e, 0x5a,
	0x0c, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shortest_path_proto_rawDescOnce sync.Once
	file_shortest_path_proto_rawDescData = file_shortest_path_proto_rawDesc
)

func file_shortest_path_proto_rawDescGZIP() []byte {
	file_shortest_path_proto_rawDescOnce.Do(func() {
		file_shortest_path_proto_rawDescData = protoimpl.X.CompressGZIP(file_shortest_path_proto_rawDescData)
	})
	return file_shortest_path_proto_rawDescData
}

var file_shortest_path_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shortest_path_proto_goTypes = []interface{}{
	(*SPRequest)(nil),  // 0: horizon.SPRequest
	(*SPResponse)(nil), // 1: horizon.SPResponse
}
var file_shortest_path_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shortest_path_proto_init() }
func file_shortest_path_proto_init() {
	if File_shortest_path_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shortest_path_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shortest_path_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shortest_path_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shortest_path_proto_goTypes,
		DependencyIndexes: file_shortest_path_proto_depIdxs,
		MessageInfos:      file_shortest_path_proto_msgTypes,
	}.Build()
	File_shortest_path_proto = out.File
	file_shortest_path_proto_rawDesc = nil
	file_shortest_path_proto_goTypes = nil
	file_shortest_path_proto_depIdxs = nil
}
