// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: shortest_path.proto

package protos_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User's request for finding shortest path
type SPRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max radius of search for potential candidates (in range [7, 50], default is 25.0)
	// Example: 10.0
	StateRadius *float64 `protobuf:"fixed64,1,opt,name=state_radius,json=stateRadius,proto3,oneof" json:"state_radius,omitempty"`
	// Set of GPS data
	Gps           []*GeoPoint `protobuf:"bytes,2,rep,name=gps,proto3" json:"gps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SPRequest) Reset() {
	*x = SPRequest{}
	mi := &file_shortest_path_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPRequest) ProtoMessage() {}

func (x *SPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortest_path_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPRequest.ProtoReflect.Descriptor instead.
func (*SPRequest) Descriptor() ([]byte, []int) {
	return file_shortest_path_proto_rawDescGZIP(), []int{0}
}

func (x *SPRequest) GetStateRadius() float64 {
	if x != nil && x.StateRadius != nil {
		return *x.StateRadius
	}
	return 0
}

func (x *SPRequest) GetGps() []*GeoPoint {
	if x != nil {
		return x.Gps
	}
	return nil
}

// Server's response for shortest path request
type SPResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of edges in a path
	Data []*EdgeInfo `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// List of warnings
	Warnings      []string `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SPResponse) Reset() {
	*x = SPResponse{}
	mi := &file_shortest_path_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPResponse) ProtoMessage() {}

func (x *SPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortest_path_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPResponse.ProtoReflect.Descriptor instead.
func (*SPResponse) Descriptor() ([]byte, []int) {
	return file_shortest_path_proto_rawDescGZIP(), []int{1}
}

func (x *SPResponse) GetData() []*EdgeInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SPResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Edge information
type EdgeInfo struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	EdgeId int64                  `protobuf:"varint,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	// Travel cost to the target vertex
	Weight float64 `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// Line
	Geom          []*GeoPoint `protobuf:"bytes,3,rep,name=geom,proto3" json:"geom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeInfo) Reset() {
	*x = EdgeInfo{}
	mi := &file_shortest_path_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeInfo) ProtoMessage() {}

func (x *EdgeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shortest_path_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeInfo.ProtoReflect.Descriptor instead.
func (*EdgeInfo) Descriptor() ([]byte, []int) {
	return file_shortest_path_proto_rawDescGZIP(), []int{2}
}

func (x *EdgeInfo) GetEdgeId() int64 {
	if x != nil {
		return x.EdgeId
	}
	return 0
}

func (x *EdgeInfo) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *EdgeInfo) GetGeom() []*GeoPoint {
	if x != nil {
		return x.Geom
	}
	return nil
}

var File_shortest_path_proto protoreflect.FileDescriptor

const file_shortest_path_proto_rawDesc = "" +
	"\n" +
	"\x13shortest_path.proto\x12\ahorizon\x1a\vpoint.proto\"i\n" +
	"\tSPRequest\x12&\n" +
	"\fstate_radius\x18\x01 \x01(\x01H\x00R\vstateRadius\x88\x01\x01\x12#\n" +
	"\x03gps\x18\x02 \x03(\v2\x11.horizon.GeoPointR\x03gpsB\x0f\n" +
	"\r_state_radius\"O\n" +
	"\n" +
	"SPResponse\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.horizon.EdgeInfoR\x04data\x12\x1a\n" +
	"\bwarnings\x18\x02 \x03(\tR\bwarnings\"b\n" +
	"\bEdgeInfo\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\x03R\x06edgeId\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\x12%\n" +
	"\x04geom\x18\x03 \x03(\v2\x11.horizon.GeoPointR\x04geomB\x0eZ\f./;protos_pbb\x06proto3"

var (
	file_shortest_path_proto_rawDescOnce sync.Once
	file_shortest_path_proto_rawDescData []byte
)

func file_shortest_path_proto_rawDescGZIP() []byte {
	file_shortest_path_proto_rawDescOnce.Do(func() {
		file_shortest_path_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortest_path_proto_rawDesc), len(file_shortest_path_proto_rawDesc)))
	})
	return file_shortest_path_proto_rawDescData
}

var file_shortest_path_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shortest_path_proto_goTypes = []any{
	(*SPRequest)(nil),  // 0: horizon.SPRequest
	(*SPResponse)(nil), // 1: horizon.SPResponse
	(*EdgeInfo)(nil),   // 2: horizon.EdgeInfo
	(*GeoPoint)(nil),   // 3: horizon.GeoPoint
}
var file_shortest_path_proto_depIdxs = []int32{
	3, // 0: horizon.SPRequest.gps:type_name -> horizon.GeoPoint
	2, // 1: horizon.SPResponse.data:type_name -> horizon.EdgeInfo
	3, // 2: horizon.EdgeInfo.geom:type_name -> horizon.GeoPoint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shortest_path_proto_init() }
func file_shortest_path_proto_init() {
	if File_shortest_path_proto != nil {
		return
	}
	file_point_proto_init()
	file_shortest_path_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortest_path_proto_rawDesc), len(file_shortest_path_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shortest_path_proto_goTypes,
		DependencyIndexes: file_shortest_path_proto_depIdxs,
		MessageInfos:      file_shortest_path_proto_msgTypes,
	}.Build()
	File_shortest_path_proto = out.File
	file_shortest_path_proto_goTypes = nil
	file_shortest_path_proto_depIdxs = nil
}
